### ISSUE TITLE
Рефакторинг createXlsxRegisters

### ISSUE THREAD

**Issue by avasyukov** [dat-cat1/alfresco-datalist-test#1]
Вот тут стартует очень суровый кусок кода:
https://github.com/dat-cat1/alfresco-datalist-test/blob/ad2beafdef778a44208856e7bbc802093acb74b0/src/main/java/com/alvexcore/repo/datalist/RegistryAsXLSX.java#L111-L117

По факту функции делают одно и то же, порождая макароны. При этом логическая нагрузка функции довольно велика, по мере жизни расширения её точно придётся допиливать.

Предлагается свести логически нагруженную часть к одной функции с сигнатурой в духе:
`Workbook createXlsxRegisters(String XLS_SHEET_NAME, List<NodeRef> datalistRecords, List<String> includeList, List<String> excludeList)`

Т.е. вынести отдельно всю логику по тому, передали нам nodeRef списка (и тогда нужно получить записи из него) или сразу набор nodeRef-ов записей.

**Comment by dtsvetkov1** [comment]
Получение nodeRef-ов записей вынесено за пределы функции, в целом все это нагромождение немного упрощено (да, сейчас функции fillRowHeader и fillRowData выполняют одно и то же, в следующей итерации этого не будет).
