### ISSUE TITLE
Определение списка полей для экспорта

### ISSUE THREAD

**Issue by avasyukov** [dat-cat1/alfresco-datalist-test#2]
Вот тут (и в пачке аналогичных мест) мы довольно опасно заложились на значения в первой ноде из списка:
https://github.com/dat-cat1/alfresco-datalist-test/blob/ad2beafdef778a44208856e7bbc802093acb74b0/src/main/java/com/alvexcore/repo/datalist/RegistryAsXLSX.java#L152-L156

А если каких-то полей нет конкретно у первой ноды?

Идейно более верно будет сделать примерно следующее:
1. Получить список нужных нам свойств в виде QName-ов. В случае include используемый resolveToQName - ок для этой цели.
2. Проверить, что свойства с такими QName правда есть в модели. Поможет dictionaryService.getProperty(fieldQName), который вернёт или null, или нет.
3. В случае exclude всё сложнее - у нас нет полного списка свойств. Опираться на заполненность полей первой ноды не будем, будем опираться на описание модели данных. Для первой ноды получаем имя её типа - nodeService.getType(nodeRef). По имени типа - полное описание типа - http://dev.alfresco.com/resource/AlfrescoOne/5.0/PublicAPI/org/alfresco/service/cmr/dictionary/DictionaryService.html#getType(org.alfresco.service.namespace.QName) Из него - полный список пропертей - http://dev.alfresco.com/resource/AlfrescoOne/5.0/PublicAPI/org/alfresco/service/cmr/dictionary/ClassDefinition.html#getProperties(). Далее на это сверху накладываем exclude.

**Comment by dtsvetkov1** [comment]
Теперь для импорта и экспорта формируются списки qname, но не все поулчилось гладко. 
1) в случае include свойства которые не найдены но (возможно) могут существовать (вида "cm:wtf") просто игнорируются и никуда не пишутся.
2) в случае с exclude все стало хуже. Теперь часть (видимо стандартных) свойств пропала (вроде "cm:created" или "sys:node-uuid") отсутствует и никак не хочет появляться в dictionaryService.getType(type1).getProperties() (есть только абстрактный cm:content, который видимо все это содержит, но как оттуда достать необходимое?). Возможно стоит в данном случае обьединить усилия с nodeService.getProperties и сгрупировать данные.

**Comment by avasyukov** [comment]
Насчёт (1) - если свойства нет в моделях вообще (если dictionaryService.getProperty(fieldQName) выдаёт на него null), то его не может быть ни у одной ноды. Так что с этим всё ок.

Насчёт (2) момент интересный. Вообще по доке http://dev.alfresco.com/resource/AlfrescoOne/5.0/PublicAPI/org/alfresco/service/cmr/dictionary/ClassDefinition.html#getProperties() я не ждал подвоха, всё должно было работать, отдавая в том числе свойства из родительских типов:
>     Returns: the properties of the class, including inherited properties
Сейчас посмотрю ещё внимательнее и глубже, wtf. (В сторону cm:content смотреть не надо, это отдельное свойство на тему где физически брать блобы для файлов, в нём других свойств нет.)

Ещё из значимого - стоит вот эту проверку:
https://github.com/dat-cat1/alfresco-datalist-test/blob/05f585c4882d6ccc5551e1f231d708f928c006ba/src/main/java/com/alvexcore/repo/datalist/RegistryAsXLSX.java#L183
вынести куда-нибудь сюда:
https://github.com/dat-cat1/alfresco-datalist-test/blob/05f585c4882d6ccc5551e1f231d708f928c006ba/src/main/java/com/alvexcore/repo/datalist/RegistryAsXLSX.java#L117-L121
Чтобы на синтаксически верное, но которого нет в модели, тоже аккуратно отдавать BAD_REQUEST.

**Comment by avasyukov** [comment]
Я наконец смог спокойно подумать насчёт полного списка полей, отталкаваясь от типа в модели. Его можно получить вот так:
```java
            Map<QName, PropertyDefinition> map = new HashMap<>();
            TypeDefinition typeDef = dictionaryService.getType(type1);
            map.putAll(typeDef.getProperties());
            List<AspectDefinition> aspects = typeDef.getDefaultAspects(true);
            for(AspectDefinition aspect : aspects) {
                Map<QName, PropertyDefinition> aspectProps = aspect.getProperties();
                map.putAll(aspectProps);
            }
```
Причина лёгкого цирка - основная масса полей описана не в самом типе (type), а в аспектах (aspects). (Аспект - логическая единица, в которой можно один раз описать поля, после чего цеплять её к разным типам.) В итоге typeDef.getProperties() работает честно, отдавая все поля, включая унаследованные - но этого мало. Поэтому с помощью typeDef.getDefaultAspects(true) получаем все аспекты для типа, включая унаследованные. Дальше из каждого аспекта достаём поля и добавляем в общий список.

**Comment by dtsvetkov1** [comment]
Добавлены аспекты, теперь в случае exclude записей выгружаются все необходимые поля.
