### ISSUE TITLE
Заполнение строк для нод с частично пустыми полями

### ISSUE THREAD

**Issue by avasyukov** [dat-cat1/alfresco-datalist-test#3]
Вот тут и в аналогичных местах
https://github.com/dat-cat1/alfresco-datalist-test/blob/ad2beafdef778a44208856e7bbc802093acb74b0/src/main/java/com/alvexcore/repo/datalist/RegistryAsXLSX.java#L167-L179
мы заполняем строчки таблицы. При этом счётчик cellNum щёлкает в цикле по ключам мапы. А мапа заполняется в зависимости от фактического наличия полей у ноды.

Что случится, если у какой-то ноды части полей нет?

Будет хорошо после реализации логики из #2 получить полный список полей для экспорта. И идти именно по нему. Нет поля у ноды (getProperty отдаёт null) - ок, записали пустую ячейку и пошли дальше.

**Comment by dtsvetkov1** [comment]
Теперь заполнение идет по полученным полям.
